// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04njs_kPbY7p12GcOyVEcYdhdarJ8MZo',
    appId: '1:47097517765:web:e92521d0b0e086198542ac',
    messagingSenderId: '47097517765',
    projectId: 'anime-verse-836c7',
    authDomain: 'anime-verse-836c7.firebaseapp.com',
    storageBucket: 'anime-verse-836c7.firebasestorage.app',
    measurementId: 'G-BEEHEL5JS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjsxLujkK58N01vT1-7LseiUb4T6iIiI',
    appId: '1:47097517765:android:6fe1b6ec71747fc08542ac',
    messagingSenderId: '47097517765',
    projectId: 'anime-verse-836c7',
    storageBucket: 'anime-verse-836c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsdINfKwTMN2L-AqcZpn7NWEJDUCcty5w',
    appId: '1:47097517765:ios:8939582724c1d9568542ac',
    messagingSenderId: '47097517765',
    projectId: 'anime-verse-836c7',
    storageBucket: 'anime-verse-836c7.firebasestorage.app',
    iosBundleId: 'com.example.animeverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsdINfKwTMN2L-AqcZpn7NWEJDUCcty5w',
    appId: '1:47097517765:ios:5c44614d9dcb31e18542ac',
    messagingSenderId: '47097517765',
    projectId: 'anime-verse-836c7',
    storageBucket: 'anime-verse-836c7.firebasestorage.app',
    iosBundleId: 'com.example.animeverse.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04njs_kPbY7p12GcOyVEcYdhdarJ8MZo',
    appId: '1:47097517765:web:6ce38a964091dba48542ac',
    messagingSenderId: '47097517765',
    projectId: 'anime-verse-836c7',
    authDomain: 'anime-verse-836c7.firebaseapp.com',
    storageBucket: 'anime-verse-836c7.firebasestorage.app',
    measurementId: 'G-MXPLSHYN2X',
  );
}
